namespace ExoplanetLibrary
    {
    partial class VisualizationDialog
        {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose (bool disposing)
            {
            if (disposing && ( components != null ))
                components.Dispose ();

            base.Dispose (disposing);
            }

        private void InitializeComponent ()
            {
            this.PlotSurface2D = new NPlot.Windows.PlotSurface2D();
            this.backgroundWorker1 = new System.ComponentModel.BackgroundWorker();
            this.menuStrip = new System.Windows.Forms.MenuStrip();
            this.visualizationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.massToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.radiiToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.orbitalPeriodToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.semiMajorAxisToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.eccentricityToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.angularDistanceToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.inclinationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.t0ToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.t0secToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.lambdaAngleToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tvrToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tcalcToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tmeasToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.loggToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.omegaToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tperiToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.kToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.geometricAlbedoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tconjToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.printStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.pointToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.massVsRadiusToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.eccentricityVsMassToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.rightAccessionVsDeclinationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.settingsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.errorBarsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.colorFromStarTypeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.refreshViewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.printPreviewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.menuStrip.SuspendLayout();
            this.SuspendLayout();
            // 
            // PlotSurface2D
            // 
            this.PlotSurface2D.AutoScaleAutoGeneratedAxes = false;
            this.PlotSurface2D.AutoScaleTitle = false;
            this.PlotSurface2D.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.PlotSurface2D.DateTimeToolTip = false;
            this.PlotSurface2D.Legend = null;
            this.PlotSurface2D.LegendZOrder = -1;
            this.PlotSurface2D.Location = new System.Drawing.Point(-5, 27);
            this.PlotSurface2D.Name = "PlotSurface2D";
            this.PlotSurface2D.RightMenu = null;
            this.PlotSurface2D.ShowCoordinates = true;
            this.PlotSurface2D.Size = new System.Drawing.Size(685, 342);
            this.PlotSurface2D.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.PlotSurface2D.TabIndex = 0;
            this.PlotSurface2D.Text = "PlotSurface2D";
            this.PlotSurface2D.Title = "";
            this.PlotSurface2D.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.PlotSurface2D.XAxis1 = null;
            this.PlotSurface2D.XAxis2 = null;
            this.PlotSurface2D.YAxis1 = null;
            this.PlotSurface2D.YAxis2 = null;
            // 
            // menuStrip
            // 
            this.menuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.visualizationToolStripMenuItem,
            this.pointToolStripMenuItem,
            this.settingsToolStripMenuItem});
            this.menuStrip.Location = new System.Drawing.Point(0, 0);
            this.menuStrip.Name = "menuStrip";
            this.menuStrip.Size = new System.Drawing.Size(684, 24);
            this.menuStrip.TabIndex = 1;
            this.menuStrip.Text = "menuStrip1";
            // 
            // visualizationToolStripMenuItem
            // 
            this.visualizationToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.massToolStripMenuItem,
            this.radiiToolStripMenuItem,
            this.orbitalPeriodToolStripMenuItem,
            this.semiMajorAxisToolStripMenuItem,
            this.eccentricityToolStripMenuItem,
            this.angularDistanceToolStripMenuItem,
            this.inclinationToolStripMenuItem,
            this.t0ToolStripMenuItem,
            this.t0secToolStripMenuItem,
            this.lambdaAngleToolStripMenuItem,
            this.tvrToolStripMenuItem,
            this.tcalcToolStripMenuItem,
            this.tmeasToolStripMenuItem,
            this.loggToolStripMenuItem,
            this.omegaToolStripMenuItem,
            this.tperiToolStripMenuItem,
            this.kToolStripMenuItem,
            this.geometricAlbedoToolStripMenuItem,
            this.tconjToolStripMenuItem,
            this.toolStripSeparator1,
            this.refreshViewToolStripMenuItem,
            this.toolStripSeparator2,
            this.printStripMenuItem,
            this.printPreviewToolStripMenuItem});
            this.visualizationToolStripMenuItem.Name = "visualizationToolStripMenuItem";
            this.visualizationToolStripMenuItem.Size = new System.Drawing.Size(109, 20);
            this.visualizationToolStripMenuItem.Text = "Data && Error Bars";
            // 
            // massToolStripMenuItem
            // 
            this.massToolStripMenuItem.Name = "massToolStripMenuItem";
            this.massToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.massToolStripMenuItem.Text = "Mass";
            this.massToolStripMenuItem.Click += new System.EventHandler(this.visualizeMass_Click);
            // 
            // radiiToolStripMenuItem
            // 
            this.radiiToolStripMenuItem.Name = "radiiToolStripMenuItem";
            this.radiiToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.radiiToolStripMenuItem.Text = "Radii";
            this.radiiToolStripMenuItem.Click += new System.EventHandler(this.visualizeRadii_Click);
            // 
            // orbitalPeriodToolStripMenuItem
            // 
            this.orbitalPeriodToolStripMenuItem.Name = "orbitalPeriodToolStripMenuItem";
            this.orbitalPeriodToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.orbitalPeriodToolStripMenuItem.Text = "Orbital Period";
            this.orbitalPeriodToolStripMenuItem.Click += new System.EventHandler(this.visualizeOrbitalPeriod_Click);
            // 
            // semiMajorAxisToolStripMenuItem
            // 
            this.semiMajorAxisToolStripMenuItem.Name = "semiMajorAxisToolStripMenuItem";
            this.semiMajorAxisToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.semiMajorAxisToolStripMenuItem.Text = "Semi-Major Axis";
            this.semiMajorAxisToolStripMenuItem.Click += new System.EventHandler(this.visualizeSemiMajorAxis_Click);
            // 
            // eccentricityToolStripMenuItem
            // 
            this.eccentricityToolStripMenuItem.Name = "eccentricityToolStripMenuItem";
            this.eccentricityToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.eccentricityToolStripMenuItem.Text = "Eccentricity";
            this.eccentricityToolStripMenuItem.Click += new System.EventHandler(this.visualizeEccentricity_Click);
            // 
            // angularDistanceToolStripMenuItem
            // 
            this.angularDistanceToolStripMenuItem.Name = "angularDistanceToolStripMenuItem";
            this.angularDistanceToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.angularDistanceToolStripMenuItem.Text = "Angular Distance";
            this.angularDistanceToolStripMenuItem.Click += new System.EventHandler(this.visualizeAngularDistance_Click);
            // 
            // inclinationToolStripMenuItem
            // 
            this.inclinationToolStripMenuItem.Name = "inclinationToolStripMenuItem";
            this.inclinationToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.inclinationToolStripMenuItem.Text = "Inclination";
            this.inclinationToolStripMenuItem.Click += new System.EventHandler(this.visualizeInclination_Click);
            // 
            // t0ToolStripMenuItem
            // 
            this.t0ToolStripMenuItem.Name = "t0ToolStripMenuItem";
            this.t0ToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.t0ToolStripMenuItem.Text = "T0";
            this.t0ToolStripMenuItem.Click += new System.EventHandler(this.visualizeT0_Click);
            // 
            // t0secToolStripMenuItem
            // 
            this.t0secToolStripMenuItem.Name = "t0secToolStripMenuItem";
            this.t0secToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.t0secToolStripMenuItem.Text = "T0-sec";
            this.t0secToolStripMenuItem.Click += new System.EventHandler(this.visualizeT0sec_Click);
            // 
            // lambdaAngleToolStripMenuItem
            // 
            this.lambdaAngleToolStripMenuItem.Name = "lambdaAngleToolStripMenuItem";
            this.lambdaAngleToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.lambdaAngleToolStripMenuItem.Text = "Lambda Angle";
            this.lambdaAngleToolStripMenuItem.Click += new System.EventHandler(this.visualizeLambdaAngle_Click);
            // 
            // tvrToolStripMenuItem
            // 
            this.tvrToolStripMenuItem.Name = "tvrToolStripMenuItem";
            this.tvrToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.tvrToolStripMenuItem.Text = "Tvr";
            this.tvrToolStripMenuItem.Click += new System.EventHandler(this.visualizeTvr_Click);
            // 
            // tcalcToolStripMenuItem
            // 
            this.tcalcToolStripMenuItem.Name = "tcalcToolStripMenuItem";
            this.tcalcToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.tcalcToolStripMenuItem.Text = "Tcalc";
            this.tcalcToolStripMenuItem.Click += new System.EventHandler(this.visualizeTcalc_Click);
            // 
            // tmeasToolStripMenuItem
            // 
            this.tmeasToolStripMenuItem.Name = "tmeasToolStripMenuItem";
            this.tmeasToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.tmeasToolStripMenuItem.Text = "Tmeas";
            this.tmeasToolStripMenuItem.Click += new System.EventHandler(this.visualizeTmeas_Click);
            // 
            // loggToolStripMenuItem
            // 
            this.loggToolStripMenuItem.Name = "loggToolStripMenuItem";
            this.loggToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.loggToolStripMenuItem.Text = "Log(g)";
            this.loggToolStripMenuItem.Click += new System.EventHandler(this.visualizeLogG_Click);
            // 
            // omegaToolStripMenuItem
            // 
            this.omegaToolStripMenuItem.Name = "omegaToolStripMenuItem";
            this.omegaToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.omegaToolStripMenuItem.Text = "Omega";
            this.omegaToolStripMenuItem.Click += new System.EventHandler(this.visualizeOmega_Click);
            // 
            // tperiToolStripMenuItem
            // 
            this.tperiToolStripMenuItem.Name = "tperiToolStripMenuItem";
            this.tperiToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.tperiToolStripMenuItem.Text = "Tperi";
            this.tperiToolStripMenuItem.Click += new System.EventHandler(this.visualizeTperi_Click);
            // 
            // kToolStripMenuItem
            // 
            this.kToolStripMenuItem.Name = "kToolStripMenuItem";
            this.kToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.kToolStripMenuItem.Text = "K";
            this.kToolStripMenuItem.Click += new System.EventHandler(this.visualizeK_Click);
            // 
            // geometricAlbedoToolStripMenuItem
            // 
            this.geometricAlbedoToolStripMenuItem.Name = "geometricAlbedoToolStripMenuItem";
            this.geometricAlbedoToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.geometricAlbedoToolStripMenuItem.Text = "Geometric Albedo";
            this.geometricAlbedoToolStripMenuItem.Click += new System.EventHandler(this.visualizeGeometricAlbedo_Click);
            // 
            // tconjToolStripMenuItem
            // 
            this.tconjToolStripMenuItem.Name = "tconjToolStripMenuItem";
            this.tconjToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.tconjToolStripMenuItem.Text = "Tconj";
            this.tconjToolStripMenuItem.Click += new System.EventHandler(this.visualizeTconj_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(167, 6);
            // 
            // printStripMenuItem
            // 
            this.printStripMenuItem.Name = "printStripMenuItem";
            this.printStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.printStripMenuItem.Text = "Print...";
            this.printStripMenuItem.Click += new System.EventHandler(this.visualizePrint_Click);
            // 
            // pointToolStripMenuItem
            // 
            this.pointToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.massVsRadiusToolStripMenuItem,
            this.eccentricityVsMassToolStripMenuItem,
            this.rightAccessionVsDeclinationToolStripMenuItem});
            this.pointToolStripMenuItem.Name = "pointToolStripMenuItem";
            this.pointToolStripMenuItem.Size = new System.Drawing.Size(47, 20);
            this.pointToolStripMenuItem.Text = "Point";
            // 
            // massVsRadiusToolStripMenuItem
            // 
            this.massVsRadiusToolStripMenuItem.Name = "massVsRadiusToolStripMenuItem";
            this.massVsRadiusToolStripMenuItem.Size = new System.Drawing.Size(235, 22);
            this.massVsRadiusToolStripMenuItem.Text = "Mass vs Radius";
            this.massVsRadiusToolStripMenuItem.Click += new System.EventHandler(this.visualizeMassVersusRadius_Click);
            // 
            // eccentricityVsMassToolStripMenuItem
            // 
            this.eccentricityVsMassToolStripMenuItem.Name = "eccentricityVsMassToolStripMenuItem";
            this.eccentricityVsMassToolStripMenuItem.Size = new System.Drawing.Size(235, 22);
            this.eccentricityVsMassToolStripMenuItem.Text = "Eccentricity vs Mass";
            this.eccentricityVsMassToolStripMenuItem.Click += new System.EventHandler(this.visualizeEccentricityVersusMass_Click);
            // 
            // rightAccessionVsDeclinationToolStripMenuItem
            // 
            this.rightAccessionVsDeclinationToolStripMenuItem.Name = "rightAccessionVsDeclinationToolStripMenuItem";
            this.rightAccessionVsDeclinationToolStripMenuItem.Size = new System.Drawing.Size(235, 22);
            this.rightAccessionVsDeclinationToolStripMenuItem.Text = "Right Accession vs Declination";
            this.rightAccessionVsDeclinationToolStripMenuItem.Click += new System.EventHandler(this.visualizeStars_Click);
            // 
            // settingsToolStripMenuItem
            // 
            this.settingsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.errorBarsToolStripMenuItem,
            this.colorFromStarTypeToolStripMenuItem});
            this.settingsToolStripMenuItem.Name = "settingsToolStripMenuItem";
            this.settingsToolStripMenuItem.Size = new System.Drawing.Size(70, 20);
            this.settingsToolStripMenuItem.Text = "Settings...";
            // 
            // errorBarsToolStripMenuItem
            // 
            this.errorBarsToolStripMenuItem.Name = "errorBarsToolStripMenuItem";
            this.errorBarsToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.errorBarsToolStripMenuItem.Text = "IncludeError Bars";
            this.errorBarsToolStripMenuItem.CheckStateChanged += new System.EventHandler(this.MenuCheckBox_CheckStateChanged);
            this.errorBarsToolStripMenuItem.Click += new System.EventHandler(this.MenuCheckBox_Click);
            // 
            // colorFromStarTypeToolStripMenuItem
            // 
            this.colorFromStarTypeToolStripMenuItem.Name = "colorFromStarTypeToolStripMenuItem";
            this.colorFromStarTypeToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.colorFromStarTypeToolStripMenuItem.Text = "Color by Star Type";
            this.colorFromStarTypeToolStripMenuItem.CheckStateChanged += new System.EventHandler(this.MenuCheckBox_CheckStateChanged);
            this.colorFromStarTypeToolStripMenuItem.Click += new System.EventHandler(this.MenuCheckBox_Click);
            // 
            // refreshViewToolStripMenuItem
            // 
            this.refreshViewToolStripMenuItem.Name = "refreshViewToolStripMenuItem";
            this.refreshViewToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.refreshViewToolStripMenuItem.Text = "Refresh View";
            this.refreshViewToolStripMenuItem.Click += new System.EventHandler(this.visualizeRefreshView_Click);
            // 
            // printPreviewToolStripMenuItem
            // 
            this.printPreviewToolStripMenuItem.Name = "printPreviewToolStripMenuItem";
            this.printPreviewToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.printPreviewToolStripMenuItem.Text = "Print Preview...";
            this.printPreviewToolStripMenuItem.Click += new System.EventHandler(this.visualizePrintPreview_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(167, 6);
            // 
            // VisualizationDialog
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.ClientSize = new System.Drawing.Size(684, 371);
            this.Controls.Add(this.PlotSurface2D);
            this.Controls.Add(this.menuStrip);
            this.MainMenuStrip = this.menuStrip;
            this.Name = "VisualizationDialog";
            this.ShowIcon = false;
            this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show;
            this.Text = "Visualization";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Visualization_FormClosing);
            this.menuStrip.ResumeLayout(false);
            this.menuStrip.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

            }

        public NPlot.Windows.PlotSurface2D PlotSurface2D;
        private System.ComponentModel.BackgroundWorker backgroundWorker1;
        private System.Windows.Forms.MenuStrip menuStrip;
        private System.Windows.Forms.ToolStripMenuItem visualizationToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem massToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem radiiToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem orbitalPeriodToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem semiMajorAxisToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem eccentricityToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem angularDistanceToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem inclinationToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem t0ToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem t0secToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem lambdaAngleToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem tvrToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem tcalcToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem tmeasToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem loggToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem omegaToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem tperiToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem pointToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem massVsRadiusToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem eccentricityVsMassToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem kToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem geometricAlbedoToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem tconjToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem rightAccessionVsDeclinationToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem printStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem settingsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem errorBarsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem colorFromStarTypeToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem refreshViewToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem printPreviewToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        }
    }